### ISSUE TITLE
Don't run baseline package validation during NuGet publishing for major version changes (OSOE-857)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#350]
To allow breaking changes in major versions, something that the [baseline package validator](https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/package-validation/baseline-version-validator) we use during NuGet publishing doesn't do (see https://github.com/dotnet/sdk/issues/40907), let's not run it in such cases.

So, if `New-NuGetPackage` notices a major version change (e.g. from 1.2.3 to 2.0.0) then disable baseline package validation (but only that, package validation should otherwise run).

If https://github.com/dotnet/sdk/issues/40907 is implemented before, then this won't be needed. If it's not yet, then link it from code.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-857)

**Comment by Piedone** [comment]
@sarahelsaig wasn't this an issue for you for https://github.com/Lombiq/Helpful-Libraries/releases/tag/v10.0.0?

**Comment by sarahelsaig** [comment]
No,  when I pushed a major tag it always worked.

**Comment by Piedone** [comment]
That's what I remembered doing before, but still, I had to do https://github.com/Lombiq/UI-Testing-Toolbox/commit/803e87f553dc16885995616958bd4a08ea3d8644 to publish a new major version. It failed under https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/9100082776/job/25014098526 without it.

**Comment by Piedone** [comment]
This seems to br working well now.

**Comment by Piedone** [comment]
Still happens sometimes: https://github.com/Lombiq/Orchard-Privacy/commit/c7ea07e88ee68ac68bcb839902bec5b06ddd6e64#commitcomment-149971985
